title: <p align="center"> Pradeep Sharma </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="#">Resume</a> |
  <a href="https://www.linkedin.com/in/pradeep-sharma-44451426/">LinkedIn</a> |
  <a href="https://github.com/pradeepksharma22">GitHub</a>
  <span>   
  I'm working on Data Science, Enterprise Search( Coveo Search, Apache Solr, Elastic Search, Lucidworks Fusion), Spark, Machine learning & NLP related problems.<br>
  Also handing the complex search problems using above search technologies.<br>
  Worked with Interglobe Technologies in GDS integration team.<br>
  Working in Search domain for 7 years.
  <span>
  </p>

show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
